# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'citibike'
version: '1.0.0'
config-version: 2

# This setting configures which profile dbt uses for this project. See profiles.yml.
profile: 'snowflake-demo'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
# Snowflake configurations: https://docs.getdbt.com/reference/resource-configs/snowflake-configs

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    citibike:
        +database: citibike
        +materialized: table
        +transient: false
        +query_tag: 'Citibike dbt demo'
        demo:
            +schema: demo
        utils:
            +schema: utils
            +tags: 'base_models'

# Seed (data) configuration
seeds:
    citibike:
        +tags: 'base_models'
        utils:
            +quote_columns: false
            +schema: utils
